trigger:
  - master
  - feat/*

schedules:
  - cron: "0 12 * * 0"
    displayName: Weekly Sunday build
    always: true

variables:
  - group: azure-demos-config
  - name: repository
    value: $(registry-host)/$(registry-namespace)
  - name: imageName
    value: $(repository)/$(app-name)
  - name: imageTag
    value: $(Build.BuildId)-$(Build.SourceVersion)

stages:
- stage: Tests
  displayName: 'Test (Node.js)'
  jobs:
    - job: Audit
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - script: npm audit
        displayName: Audit Dependencies
        continueOnError: true

    - job: Linter
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - script: npm ci && npm run lint
        displayName: Lint Code

    - job: UnitTests
      displayName: Unit Tests
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - script: npm ci && npm run test
        displayName: Run Tests

# ----------------------------
# Docker Image: Build and Push
# ----------------------------

- stage: BuildImage
  displayName: 'Build (Docker)'
  jobs:
    - job: build_and_push_image
      displayName: Build and Push Image
      steps:

      - script: docker build --tag $(imageName):$(imageTag) .
        displayName: 'Docker: Build and tag image'

      - task: Docker@1
        displayName: 'Push an image'
        inputs:
          azureSubscriptionEndpoint: $(service-connection-name)
          azureContainerRegistry: $(registry-host)
          imageName: $(imageName):$(imageTag)
          command: push

# ----------------------------
# Deploy to Azure App Services
# ----------------------------

- stage: DeployImage
  displayName: Deploy
  jobs:
  - job: deploy_image
    displayName: 'Deploy Image (master)'
    steps:
    - task: AzureWebAppContainer@1
      displayName: Deploy container as Azure Web App
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        appName: $(app-services-name)
        azureSubscription: $(service-connection-name)
        imageName: $(imageName):$(imageTag)